
# configuration 1
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "cpg_enrichment_1_rep_in_cpg"
cell_type: "NSC"
alignment_type: "no_dedup"
peaks_type: "broad"

# configuration 2
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "cpg_enrichment_2_rep_in_cpg"
cell_type: "NSC"
alignment_type: "no_dedup"
peaks_type: "broad"

# configuration 3
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "cpg_enrichment_1_rep_in_peaks"
cell_type: "NSC"
alignment_type: "no_dedup"
peaks_type: "broad"


# configuration 4
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "cpg_enrichment_2_rep_in_peaks"
cell_type: "NSC"
alignment_type: "no_dedup"
peaks_type: "broad"


# configuration 5
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "cpg_enrichment_1_rep_in_cpg"
cell_type: "Neu"
alignment_type: "no_dedup"
peaks_type: "broad"

# configuration 6
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "cpg_enrichment_2_rep_in_cpg"
cell_type: "Neu"
alignment_type: "no_dedup"
peaks_type: "broad"

# configuration 7
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "cpg_enrichment_1_rep_in_peaks"
cell_type: "Neu"
alignment_type: "no_dedup"
peaks_type: "broad"


# configuration 8
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "cpg_enrichment_2_rep_in_peaks"
cell_type: "Neu"
alignment_type: "no_dedup"
peaks_type: "broad"


# configuration 9
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "neu_vs_nsc_exo"
alignment_type: "no_dedup"
peaks_type: "broad"

# configuration 10
---
base_dir: "D:/Github/SRF_MeCP2_cut_tag/iterative_alternative"
run_name: "neu_vs_nsc_endo"
alignment_type: "no_dedup"
peaks_type: "broad"
